[opener]
text = [
  { exec = 'nvim "%*"', block = true },
]

[open]
rules = [
  { name = "*.md", use = "text" },

  # Multiple openers for a single rule
  { name = "*.html", use = [ "browser", "text" ] },
]
