source ~/.config/zsh/fzf.zsh
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/prompt.zsh
source ~/.local/share/zinit/zinit.git/zinit.zsh
source ~/.config/zsh/plugins.zsh
source ~/.config/zsh/yazi.zsh
source ~/.config/zsh/arch-zsh-config
source ~/.config/zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh
source <(fzf --zsh)

# setup editor
export EDITOR='nvim'

# setup for bat
export BAT_THEME="Catppuccin-mocha"
export BAT_STYLE="changes"

# auto startx
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec startx
fi
