source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/yazi.zsh

# setup for plugin
source ~/.local/share/zinit/zinit.git/zinit.zsh
source ~/.config/zsh/plugins.zsh
source ~/.config/zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh

# setup for fzf
source ~/.config/zsh/fzf.zsh
source <(fzf --zsh)

# setup prompt
export PROMPT="%F{147}%n%f@%F{183}%m%f %F{225}%~%f \$ "

# setup for bat
export BAT_THEME="Catppuccin-mocha"
export BAT_STYLE="changes"

# auto startx
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec startx
fi
