# setup theme
ZSH_THEME="catppuccin"
CATPPUCCIN_FLAVOR="mocha"

bindkey -e

# setup for plugin
source ~/.local/share/zinit/zinit.git/zinit.zsh
source ${0:A:h}/plugins.zsh

# setup for fzf
source ${0:A:h}/fzf.zsh
source <(fzf --zsh)

source ${0:A:h}/aliases.zsh
source ${0:A:h}/yazi.zsh
source ${0:A:h}/prompt.zsh

# setup for bat
export BAT_THEME="Catppuccin-mocha"
export BAT_STYLE="changes"

# setup for pnpm
export PNPM_HOME="/home/gin/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

# set default editor
export EDITOR=nvim

# auto startx
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
  exec startx
fi
